env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
sudo: false
language: node_js
node_js:
- '0.12'
script: npm test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: E4BYsUC1Vvz/Asgy9yiVqFUqIvcITbET/+A0dDTr+2XaTjwRZVLnCkRfixF96u5Tz4tfqyS5w4hRKMfNx36idNxszmaev3HWl1hQW5UtuL7BzXQTDEruLq1TcgqglOMehlAHIAGBtpEj+ctnJ4vuHb/gQZLsWHpLy2CBOsQMELk=
  app: scheduler-taskcluster-net
  on:
    repo: taskcluster/task-graph-scheduler
before_install:
- openssl aes-256-cbc -K $encrypted_15e469258d4f_key -iv $encrypted_15e469258d4f_iv
  -in task-graph-scheduler.conf.json.enc -out task-graph-scheduler.conf.json -d
