env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
sudo: false
language: node_js
node_js:
- '0.12'
script: npm test
before_install:
- openssl aes-256-cbc -K $encrypted_15e469258d4f_key -iv $encrypted_15e469258d4f_iv
  -in task-graph-scheduler.conf.json.enc -out task-graph-scheduler.conf.json -d
